import Head from 'next/head'
import Image from 'next/image'
import Content from '../components/Content'
import Header from '../components/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />

        <Content />
      </main>

    </div>
  )
}
